"""
Claude AI Signal Validator
Validates trading signals using Claude AI for quality assessment
"""
import os
import logging
from typing import Dict, Optional
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

class AIValidator:
    """
    Uses Claude AI to validate trading signals
    """
    
    def __init__(self):
        self.api_key = os.getenv('EMERGENT_LLM_KEY')
        self.model = 'claude-4-sonnet-20250514'
    
    async def validate_signal(self, signal_data: Dict) -> Dict:
        """
        Validate a trading signal using Claude AI
        
        Input signal_data:
        - instrument: str (e.g., "NIFTY")
        - ltp: float (last traded price)
        - direction: str ("BUY" or "SELL")
        - score: float (confluence score)
        - indicators_agreeing: int
        - votes: list of indicator votes
        - stop_loss: float
        - take_profit: float
        - risk_reward: float
        
        Returns:
        - verdict: str (STRONG_BUY, BUY, WEAK_BUY, NEUTRAL, WEAK_SELL, SELL, STRONG_SELL)
        - quality: str (EXCELLENT, GOOD, FAIR, POOR)
        - confidence: float (0-100)
        - entry_timing: str (OPTIMAL, ACCEPTABLE, SUBOPTIMAL)
        - key_risk: str
        - adjustment: str (suggestions for improving the trade)
        """
        if not self.api_key:
            return self._default_validation(signal_data)
        
        try:
            from emergentintegrations.llm.chat import LlmChat, UserMessage
            
            # Build the prompt
            prompt = self._build_validation_prompt(signal_data)
            
            # Initialize Claude chat
            chat = LlmChat(
                api_key=self.api_key,
                session_id=f"signal_validation_{signal_data.get('instrument', 'unknown')}",
                system_message="""You are an expert algorithmic trading analyst. Your role is to validate trading signals
generated by a multi-indicator confluence scoring system. Analyze the provided signal data and provide
a structured assessment. Be concise but thorough. Focus on risk management and signal quality."""
            ).with_model('anthropic', self.model)
            
            # Send message
            user_message = UserMessage(text=prompt)
            response = await chat.send_message(user_message)
            
            # Parse response
            return self._parse_ai_response(response, signal_data)
            
        except Exception as e:
            logger.error(f'AI validation error: {e}')
            return self._default_validation(signal_data)
    
    def _build_validation_prompt(self, signal_data: Dict) -> str:
        """Build the validation prompt for Claude"""
        votes_text = "\n".join([
            f"  - {v['name']}: {'BULLISH' if v['vote'] > 0 else 'BEARISH' if v['vote'] < 0 else 'NEUTRAL'} (weight: {v['weight']}) - {v['detail']}"
            for v in signal_data.get('votes', [])
        ])
        
        return f"""TRADING SIGNAL VALIDATION REQUEST

Instrument: {signal_data.get('instrument', 'UNKNOWN')}
Last Traded Price: {signal_data.get('ltp', 0)}
Signal Direction: {signal_data.get('direction', 'NEUTRAL')}
Confluence Score: {signal_data.get('score', 0)}
Indicators Agreeing: {signal_data.get('indicators_agreeing', 0)}/10
Confidence: {signal_data.get('confidence', 0)}%

Stop Loss: {signal_data.get('stop_loss', 0)}
Take Profit: {signal_data.get('take_profit', 0)}
Risk:Reward Ratio: {signal_data.get('risk_reward', 0)}:1
ATR: {signal_data.get('atr', 0)}

INDICATOR BREAKDOWN:
{votes_text}

Please provide your assessment in the following format:
VERDICT: [STRONG_BUY/BUY/WEAK_BUY/NEUTRAL/WEAK_SELL/SELL/STRONG_SELL]
QUALITY: [EXCELLENT/GOOD/FAIR/POOR]
CONFIDENCE: [0-100]%
ENTRY_TIMING: [OPTIMAL/ACCEPTABLE/SUBOPTIMAL]
KEY_RISK: [One line description of the main risk]
ADJUSTMENT: [One line suggestion for trade improvement, if any]"""
    
    def _parse_ai_response(self, response: str, signal_data: Dict) -> Dict:
        """Parse Claude's response into structured data"""
        result = {
            'verdict': 'NEUTRAL',
            'quality': 'FAIR',
            'confidence': 50,
            'entry_timing': 'ACCEPTABLE',
            'key_risk': 'Market volatility',
            'adjustment': 'Consider waiting for additional confirmation',
            'raw_response': response
        }
        
        lines = response.split('\n')
        for line in lines:
            line = line.strip()
            if line.startswith('VERDICT:'):
                verdict = line.replace('VERDICT:', '').strip().upper()
                if verdict in ['STRONG_BUY', 'BUY', 'WEAK_BUY', 'NEUTRAL', 'WEAK_SELL', 'SELL', 'STRONG_SELL']:
                    result['verdict'] = verdict
            elif line.startswith('QUALITY:'):
                quality = line.replace('QUALITY:', '').strip().upper()
                if quality in ['EXCELLENT', 'GOOD', 'FAIR', 'POOR']:
                    result['quality'] = quality
            elif line.startswith('CONFIDENCE:'):
                try:
                    conf = line.replace('CONFIDENCE:', '').replace('%', '').strip()
                    result['confidence'] = min(100, max(0, int(float(conf))))
                except:
                    pass
            elif line.startswith('ENTRY_TIMING:'):
                timing = line.replace('ENTRY_TIMING:', '').strip().upper()
                if timing in ['OPTIMAL', 'ACCEPTABLE', 'SUBOPTIMAL']:
                    result['entry_timing'] = timing
            elif line.startswith('KEY_RISK:'):
                result['key_risk'] = line.replace('KEY_RISK:', '').strip()
            elif line.startswith('ADJUSTMENT:'):
                result['adjustment'] = line.replace('ADJUSTMENT:', '').strip()
        
        return result
    
    def _default_validation(self, signal_data: Dict) -> Dict:
        """Provide default validation when AI is unavailable"""
        score = abs(signal_data.get('score', 0))
        agreeing = signal_data.get('indicators_agreeing', 0)
        direction = signal_data.get('direction', 'NEUTRAL')
        rr = signal_data.get('risk_reward', 0)
        
        # Determine verdict based on score and agreeing indicators
        if direction == 'NEUTRAL':
            verdict = 'NEUTRAL'
        elif score >= 7 and agreeing >= 8:
            verdict = f'STRONG_{direction}'
        elif score >= 5 and agreeing >= 6:
            verdict = direction
        elif score >= 3 and agreeing >= 4:
            verdict = f'WEAK_{direction}'
        else:
            verdict = 'NEUTRAL'
        
        # Determine quality
        if score >= 7 and rr >= 2:
            quality = 'EXCELLENT'
        elif score >= 5 and rr >= 1.5:
            quality = 'GOOD'
        elif score >= 3:
            quality = 'FAIR'
        else:
            quality = 'POOR'
        
        # Determine entry timing
        if agreeing >= 7:
            timing = 'OPTIMAL'
        elif agreeing >= 5:
            timing = 'ACCEPTABLE'
        else:
            timing = 'SUBOPTIMAL'
        
        return {
            'verdict': verdict,
            'quality': quality,
            'confidence': min(100, int(score * 10 + agreeing * 5)),
            'entry_timing': timing,
            'key_risk': 'Market conditions may change rapidly',
            'adjustment': 'Monitor for confirmation before entry' if timing != 'OPTIMAL' else 'Signal looks optimal',
            'ai_available': False
        }
